#!/bin/bash
# Only run for interactive bash shells
if [[ $- != *i* ]]; then
	return 0 2>/dev/null || exit 0
fi
# An alternative to the above
# [[ $- != *i* ]] && return

# Prompt: show host, working dir, and mark failed last command
PS1='$(if [ $? -ne 0 ]; then echo "[FAIL] "; fi)\h:\w\$ '

## Don't set vi mode, that screws up the Ctrl+l mapping
## Instead we should prefer the emacs mode in the terminal
## Use vim keybindings (like `bindkey -v` in zsh)
#set -o vi
set -o emacs

# History
HISTSIZE=1000
HISTFILESIZE=1000
HISTFILE=~/.bash_history

# Enable system bash completions if available
if [ -f /etc/bash_completion ]; then
	# shellcheck disable=SC1091
	. /etc/bash_completion
fi

# Terminfo / LS colors
eval "$(dircolors -b)"

# Aliases
alias ls='ls -F'
alias bt_battery="bluetooth_battery 34:75:63:DA:AA:C5"

YARN_PATH=$(yarn global bin)

# Environment
export PYSPARK_PYTHON=python3
export PYSPARK_DRIVER_PYTHON=${PYSPARK_PYTHON}
export LESS=dMQifRF
export LESSCHARSET=utf-8
export GOPATH=$HOME/go
export GOROOT=/usr/local/go
export PATH=$YARN_PATH:$HOME/.pipinstall/bin:$GOROOT/bin:$GOPATH/bin:/usr/local/go/bin:$HOME/.local/bin:$PATH
export GOFLAGS="-tags=aws"
export GOPRIVATE="*.se.axis.com"

# Notices
[ -f /var/run/reboot-required ] && echo "System needs to reboot!"

# Kill the bell
xset -b

# ripgrep->fzf->vim helper
# For file contents searching
rfv() {
	RELOAD='reload:rg --column --color=always --smart-case {q} || :'
	OPENER='if [[ $FZF_SELECT_COUNT -eq 0 ]]; then
						vim {1} +{2}
					else
						vim +cw -q {+f}
					fi'
	fzf --disabled --ansi --multi \
			--bind "start:$RELOAD" --bind "change:$RELOAD" \
			--bind "enter:become:$OPENER" \
			--bind "ctrl-o:execute:$OPENER" \
			--bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
			--delimiter : \
			--preview 'batcat --style=full --color=always --highlight-line {2} {1}' \
			--preview-window '~4,+{2}+4/3,<80(up)' \
			--query "$*"
}

# fdfind->fzf->vim helper
# For file name searching
ffv() {
    fdfind | fzf --preview 'batcat {}'
}

#######################
# Git helpers
#######################

prune_branches() {
    # We assume that this function is executed within a git repo.

    # Fetch and prune first so upstream tracking status is accurate.
    git fetch --prune

    # Is the current branch's upstream gone?
    local upstream_status
    upstream_status=$(git for-each-ref --format='%(upstream:track)' "refs/heads/$(git branch --show-current)")
    if [[ "$upstream_status" == "[gone]" ]]; then
        # If so, switch to main so we can delete this branch below.
        echo "Moving to main branch since the current branch's upstream is gone."
        git checkout main
        git pull
    fi

    # Prune all local branches whose upstream is gone.
    git for-each-ref --format='%(refname:short) %(upstream:track)' refs/heads/ | while read -r branch upstream; do
        if [[ "$upstream" == "[gone]" ]]; then
            git branch -D "$branch"
        fi
    done
}

#######################
# Kubernetes helpers
#######################

alias k=kubectl

kns() {
    if [ -z "$1" ]; then
        kubectl get namespaces
    else
        kubectl config set-context --current --namespace="$1"
    fi
}

kctx() {
    if [ -z "$1" ]; then
        kubectl config get-contexts | sed -e 's/  \+/ /g' | cut -d' ' -f-2
    else
        kubectl config use-context "$1"
    fi
}
