" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Initialize plugin system
call plug#end()

let g:coc_global_extensions = ['coc-json', 'coc-go', 'coc-jedi', 'coc-diagnostic', 'coc-omnisharp', 'coc-java']

scriptencoding utf-8
set filetype=off

set backspace=indent,eol

syntax enable

set expandtab

" Enable hybrid line numbers
set number
set relativenumber

set ignorecase
set smartcase
set incsearch

set autoindent
set smartindent

set softtabstop=4
set tabstop=4
set shiftwidth=4

" Make sure comments continue on <ENTER> and starting new lines with o
set formatoptions+=ro

set laststatus=2

set hlsearch

set scrolloff=5

"set background=light

set modeline

" Make Vim automatically refresh any files that haven't been edited by Vim
set autoread

" Highlight space error
:highlight ExtraWhitespace term=inverse gui=inverse cterm=inverse
" Show trailing white space and when tabs and space are mixed, also highlight
" when we have more than one white space between non-white space characters
:match ExtraWhitespace /^\s\+$\|\s\+$\|S\s\{2,\}\S\|\t\+ \+/

:set cursorline

" What indentation looks like
set listchars=tab:▷⋅

filetype plugin indent on

set statusline=%t[%f][%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%y%r%m%=L%l,C%c\ %P

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

set diffopt=vertical,filler,context:3

au BufNewFile,BufRead Jenkinsfile setf groovy

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END
