" Set PYTHONPATH so that the plugins don't have to care
let $PYTHONPATH = expand('~/.vim/python/lib') . ($PYTHONPATH ? ':' . $PYTHONPATH : '')

" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}
"Plug 'Vimjas/vint'

" Initialize plugin system
call plug#end()

let g:coc_global_extensions = ['coc-xml', 'coc-markdownlint', 'coc-diagnostic', 'coc-json']

" Set leader key to comma (easy to type)
let mapleader = ','

scriptencoding utf-8
set filetype=off

set backspace=indent,eol

syntax enable

set expandtab

" Enable hybrid line numbers
set number
set relativenumber

set ignorecase
set smartcase
set incsearch

set autoindent
set smartindent

set softtabstop=4
set tabstop=4
set shiftwidth=4

" Make sure comments continue on <ENTER> and starting new lines with o, start
" new line when textwidth is set.
set formatoptions+=rot

set laststatus=2

set hlsearch

set background=dark

set scrolloff=5

set modeline

" Make Vim automatically refresh any files that haven't been edited by Vim
set autoread

" Highlight space error
:highlight ExtraWhitespace term=inverse gui=inverse cterm=inverse
" Show trailing white space and when tabs and space are mixed, also highlight
" when we have more than one white space between non-white space characters
:match ExtraWhitespace /^\s\+$\|\s\+$\|S\s\{2,\}\S\|\t\+ \+/

:set cursorline

" What indentation looks like
set listchars=tab:▷⋅

filetype plugin indent on

set statusline=%t[%f][%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%y%r%m%=L%l,C%c\ %P

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

set diffopt=vertical,filler,context:3

au BufNewFile,BufRead Jenkinsfile setf groovy

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Let Vim know we are targeting POSIX compliance
let g:is_posix = 1

" Wipe out all whitespace at the end of a line
autocmd BufWritePre * :silent! %s/\s\+$//
autocmd FileType docbk set ft=xml

" let $NVIM_COC_LOG_LEVEL = 'trace'
